import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
const inter = Inter({ subsets: ["latin"] });

const YekanBakhFont = localFont({
  src: "../../public/fonts/Farsi Numerals/Webfonts/woff/YekanBakhFaNum-Regular.woff",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa-ir" dir="rtl">
      <body className={YekanBakhFont.className}>{children}</body>
    </html>
  );
}
